// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDdaQNrJ__b1bTRHBprbJPi5w9i12LCx8',
    appId: '1:1082089304189:web:87be0bf82207e1d140c114',
    messagingSenderId: '1082089304189',
    projectId: 'vigilionx',
    authDomain: 'vigilionx.firebaseapp.com',
    storageBucket: 'vigilionx.firebasestorage.app',
    measurementId: 'G-Q8BGVQQ4PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6cg3UFy30i1I1rZGkzC9iBhNkWTwGcV0',
    appId: '1:1082089304189:android:c62194c3faa935a540c114',
    messagingSenderId: '1082089304189',
    projectId: 'vigilionx',
    storageBucket: 'vigilionx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5v5TiY6n5zucDhwdj-ni_4Cj6LNAlhno',
    appId: '1:1082089304189:ios:3cf2d16a7bba228a40c114',
    messagingSenderId: '1082089304189',
    projectId: 'vigilionx',
    storageBucket: 'vigilionx.firebasestorage.app',
    iosBundleId: 'com.vigilionx.vigilionx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5v5TiY6n5zucDhwdj-ni_4Cj6LNAlhno',
    appId: '1:1082089304189:ios:3cf2d16a7bba228a40c114',
    messagingSenderId: '1082089304189',
    projectId: 'vigilionx',
    storageBucket: 'vigilionx.firebasestorage.app',
    iosBundleId: 'com.vigilionx.vigilionx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDdaQNrJ__b1bTRHBprbJPi5w9i12LCx8',
    appId: '1:1082089304189:web:331cc6183596a85940c114',
    messagingSenderId: '1082089304189',
    projectId: 'vigilionx',
    authDomain: 'vigilionx.firebaseapp.com',
    storageBucket: 'vigilionx.firebasestorage.app',
    measurementId: 'G-7Y43TVB75E',
  );
}
